Con 3188 Create new provider permissions page
SkillsFundingAgency/das-provider-relationships pull request #118
Opened 2021-04-07 08:55 UTC by Howesy77

2021-04-15 15:48 UTC, cofaulco commented on src/SFA.DAS.ProviderRelationships.Web/Controllers/AccountProviderLegalEntitiesController.cs
> +                ModelState.AddModelError("confirmation", "Please confirm you are sure you want to change permissions");
should these be separate viewmodels so that the [Required] attribute can be used rather than making it optional in 1 action method and compulsory in the next.

2021-04-15 15:51 UTC, cofaulco commented on src/SFA.DAS.ProviderRelationships.Web/Controllers/AccountProviderLegalEntitiesController.cs
> +        [Route("Confirm")]
This controller action is doing quite a lot, but there don't seem to be any unit tests

2021-04-15 16:00 UTC, cofaulco commented on src/SFA.DAS.ProviderRelationships.Web/Controllers/AccountProviderLegalEntitiesController.cs
> +                var operations = model.Operations.Where(o => o.IsEnabled.HasValue && o.IsEnabled.Value).Select(o => o.Value).ToHashSet();
`o.IsEnabled.GetValueOrDefault()`

2021-04-15 16:15 UTC, cofaulco commented on src/SFA.DAS.ProviderRelationships.Web/ViewModels/Operations/OperationViewModel.cs
> -            if (operationtoCompare.Value == Operation.NotSet) return false;
is there any need to implement Equals() now that we have removed this line?

2021-04-15 16:18 UTC, cofaulco commented on src/SFA.DAS.ProviderRelationships/Application/Queries/GetAccountProviderLegalEntity/GetAccountProviderLegalEntityQuery.cs
> +        public GetAccountProviderLegalEntityQuery(string accountHashedId, long accountId, long accountProviderId, long accountLegalEntityId)
could we pass 1 of `accountHashedId` and `accountId` and encode/decode as necessary?

2021-04-15 16:20 UTC, cofaulco commented on src/SFA.DAS.ProviderRelationships/Services/DasRecruitService.cs
>          public async Task<VacanciesSummary> GetVacanciesAsync(
Unit tests?

2021-04-15 16:21 UTC, cofaulco requested changes
A few comments

2021-04-16 10:54 UTC, Howesy77 commented on src/SFA.DAS.ProviderRelationships.Web/Controllers/AccountProviderLegalEntitiesController.cs
> +        [Route("Confirm")]
Added test for no confirmation and change option.

2021-04-16 10:55 UTC, Howesy77 commented on src/SFA.DAS.ProviderRelationships.Web/Controllers/AccountProviderLegalEntitiesController.cs
> +                var operations = model.Operations.Where(o => o.IsEnabled.HasValue && o.IsEnabled.Value).Select(o => o.Value).ToHashSet();
Oops

2021-04-16 10:55 UTC, Howesy77 commented on src/SFA.DAS.ProviderRelationships.Web/ViewModels/Operations/OperationViewModel.cs
> -            if (operationtoCompare.Value == Operation.NotSet) return false;
Yep it's gone

2021-04-16 11:12 UTC, Howesy77 commented on src/SFA.DAS.ProviderRelationships/Application/Queries/GetAccountProviderLegalEntity/GetAccountProviderLegalEntityQuery.cs
> +        public GetAccountProviderLegalEntityQuery(string accountHashedId, long accountId, long accountProviderId, long accountLegalEntityId)
Done

2021-04-16 11:15 UTC, Howesy77 commented on src/SFA.DAS.ProviderRelationships/Services/DasRecruitService.cs
>          public async Task<VacanciesSummary> GetVacanciesAsync(
It's existing code?

2021-04-16 11:23 UTC, cofaulco approved these changes

2021-05-04 13:29 UTC, merged